language: node_js
node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules
after_success:
- yarn coverage
deploy:
  provider: npm
  email: toxictoxer@gmail.com
  on:
    tags: true
    repo: chinjs/chin-plugin-json
    branch: publish
  api_key:
    secure: 1lNBv9qCkhmmUfm1s2r3r23r4BfxCbgd6zqoFV75TPq90dEu3Zu3+YvTEwJAoSXx7i3fVSQ0nGl8ZpKaqG5ehNqYwUcBdMNCeZoBPLng+T/fuIfczFTrzpei30hm3s/n+ESPIISUN5+n0VStSxZB4K2+ERKtcBWlBbuPnoqiWY8V3QbCpw8Fq5joDVKM8dOTKd/XMCxiR5nct5d2ga8Zgf3a0B90vq/LSX+zgztl8e3WthHC3xrLQOPKI2pFEavwn+pDC1geyI5zCPEcoUOrRss+3vtqf1t/bYR9AhE3X6mhQ0CqPxdbJlWx3/KeiuM+/WHCSwDTSrg6OVi6uRJiIQBaM+I7nLuIpCh3TMW4Z2Xi0lxTRi6z2S+abaU53EW+NX0KbY61kdaxiz3ctx3ohLKp6/hTdfFxQPQlUaX/BzGC3XZX+hCMC1YWefPOobktSn73j7y/w4VKi8vXTpruui7EeYBp8AI51NPAAsrasaXRphDs/2wB+0/BIhQyvAyuLl0hr3nUqV2qmaU7ldMEFypNX5D+UUeafPBJjcIbzDp8oCfd2vdDbAY4tmGmq6dgGLUDi5oBLyms3UdWeOvAGHMsiw3hR3fYEzn79UdA3w4HzKVrtfXevNgVUCZ9FyHBHocGYZjsXUwm+CNr4eDphqq7qXEhPH+wr1hgcAhbndM=
